name: VanillaTrade
version: 1.0
main: com.tenny1028.vanillatrade.VanillaTrade

commands:
  shop:
    description: Begin shop setup.
    permission: vanillatrade.sell
    usage: None

permissions:
  vanillatrade.sell:
    default: true
    description: Allows players to setup a shop.
  vanillatrade.op:
    default: op
    description: Allows players to edit other shops.